modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="caduceus"
version="${version}"
displayName="Caduceus"
logoFile="assets/caduceus/icon.png"
authors="object-Object"
description='''A Clojure-based Hex Casting addon for advanced meta-evaluation, ported to NeoForge 1.21.1.'''
displayURL="https://github.com/object-Object/Caduceus"

[[mixins]]
config="caduceus.mixins.json"

[[dependencies.caduceus]]
modId="neoforge"
type="required"
versionRange="[21.1.234,)"
ordering="NONE"
side="BOTH"

[[dependencies.caduceus]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.caduceus]]
modId="hexcasting"
type="required"
versionRange="[0.12.0-devel-pre-35,)"
ordering="AFTER"
side="BOTH"

[[dependencies.caduceus]]
modId="kotlinforforge"
type="required"
versionRange="[5.12.0,)"
ordering="NONE"
side="BOTH"
